services:
  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jlpt-backend-prod
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  # Nginx + React Static Production Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jlpt-frontend-prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    name: jlpt-prod-network
